name: tiin_cashback
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.0
  curved_navigation_bar: ^1.0.1
  provider: ^6.0.2
  carousel_slider: ^4.0.0
  flutter_barcode_scanner: ^2.0.0
  easy_localization: ^3.0.0
  fluttertoast: ^8.0.8
  get_storage: ^2.0.3
  dio: ^4.0.4
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/nana.png
    - assets/fonts/
    - assets/languages/
    - assets/languages/ru-RU.json
    - assets/languages/uz-UZ.json

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/font.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
    - family: Meduim
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf

